<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Expense;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class ExpenseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing expenses
        DB::table('expenses')->truncate();

        // Fetch potential requestors: Drivers, Ops Admins, Super Admins
        // We exclude 'Customer' type generally.
        $requestors = \App\Models\Account::whereHas('accountType', function($q) {
            $q->whereIn('name', ['Driver', 'Operations Admin', 'Sensors Admin', 'Super Admin']); 
        })->get();

        if ($requestors->isEmpty()) {
            // Fallback if no specific users found (e.g. running seed independently)
            $requestors = \App\Models\Account::factory(3)->state(['account_type_id' => 1])->create(); // create generic
        }

        // Generate Expenses
        foreach ($requestors as $user) {
            // Each user submits 3-5 expenses
            $expenses = Expense::factory(rand(3, 5))->create([
                'account_id' => $user->id,
            ]);

            foreach($expenses as $expense) {
                // Create Transaction for the expense
                // Note: ID generation handled by DB triggers, but we need to ensure we get the ID back if possible
                // OR we just create it. Since we are in a seeder, we can just create it.
                // However, to link back to expense, we need the transaction ID.
                // Since trigger sets ID, Eloquent "create" might return object with null ID if incrementing=false.
                
                // Let's assume we need to re-fetch or use a method that returns the ID.
                // But simple create should trigger the DB.
                $transaction = \App\Models\Transaction::create([
                    'account_id' => $user->id,
                    'booking_id' => null,
                    'ticket_id' => null,
                    'transaction_date' => $expense->date,
                    'payment_method' => 'Bank Transfer',
                    'sub_total' => $expense->amount,
                    'total_amount' => $expense->amount,
                    'type' => 'Expense',
                    'status' => 'Success' 
                ]);
                
                // Refresh to get the ID generated by the trigger
                // Since trigger sets ID and incrementing=false, we must query it back manually
                $transaction = \App\Models\Transaction::where('account_id', $user->id)
                    ->where('type', 'Expense')
                    ->where('sub_total', $expense->amount)
                    ->orderBy('created_at', 'desc')
                    ->first();
                
                if ($transaction) {
                    $expense->transaction_id = $transaction->id;
                    $expense->save();
                }
            }
        }
    }
}
