<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Schedule;
use App\Models\Booking;
use App\Models\Ticket;
use App\Models\Transaction;

class BookingController extends Controller
{
    // POST /api/bookings
    public function store(Request $request)
    {
        $request->validate([
            'schedule_id' => 'required|exists:schedules,id',
            'seat_number' => 'required|string',
            'passenger_name' => 'required|string',
        ]);

        $user = $request->user(); // Get logged-in user
        $schedule = Schedule::findOrFail($request->schedule_id);

        // 1. DB TRANSACTION: Atomicity is key here.
        // If anything fails (seat taken, payment error), EVERYTHING rolls back.
        try {
            DB::beginTransaction();

            // 2. Call Stored Procedure: Check Availability
            // If seat is taken, the DB will throw an error immediately.
            DB::statement("CALL sp_check_seat_availability(?, ?)", [
                $schedule->id, 
                $request->seat_number
            ]);

            // 3. Create Booking Header
            // ID (BK-2025-...) is auto-generated by DB Trigger
            $booking = Booking::create([
                'account_id' => $user->id,
                'schedule_id' => $schedule->id,
                'booking_date' => now(),
                'total_amount' => $schedule->price_per_seat, // Assuming 1 ticket for simplicity
                'status' => 'Confirmed'
            ]);

            // We must refresh to get the generated ID from the database trigger
            $booking->refresh(); 

            // 4. Create Ticket
            $ticket = Ticket::create([
                'booking_id' => $booking->id,
                'passenger_name' => $request->passenger_name,
                'seat_number' => $request->seat_number,
                'status' => 'Valid'
            ]);

            // 5. Create Transaction (Payment Record)
            Transaction::create([
                'account_id' => $user->id,
                'booking_id' => $booking->id,
                'ticket_id' => null, // Full booking payment
                'transaction_date' => now(),
                'payment_method' => 'App Balance', // simplified
                'sub_total' => $schedule->price_per_seat,
                'total_amount' => $schedule->price_per_seat,
                'type' => 'Payment',
                'status' => 'Success'
            ]);

            DB::commit(); // Save everything

            return response()->json([
                'message' => 'Booking Successful!',
                'booking_id' => $booking->id,
                'ticket_code' => $ticket->id // Will return something like JKT251213001-BUS005-02
            ], 201);

        } catch (\Exception $e) {
            DB::rollBack(); // Undo everything if error

            // Handle the specific error from our Stored Procedure
            if (str_contains($e->getMessage(), 'Seat')) {
                return response()->json(['error' => 'That seat is already taken.'], 409);
            }

            return response()->json(['error' => 'Booking failed: ' . $e->getMessage()], 500);
        }
    }

    // GET /api/my-bookings
    public function index(Request $request)
    {
        $bookings = Booking::with(['tickets', 'schedule.route'])
            ->where('account_id', $request->user()->id)
            ->orderBy('booking_date', 'desc')
            ->get();

        return response()->json($bookings);
    }
}