<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Schedule;
use App\Models\Booking;
use App\Models\Ticket;
use App\Models\Transaction;
use App\Notifications\BookingConfirmed;
use Carbon\Carbon;

class BookingController extends Controller
{
    // POST /api/bookings
    public function store(Request $request)
    {
        // 1. Validate the Request
        $request->validate([
            'schedule_id' => 'required|exists:schedules,id',
            'travel_date' => 'required|date|after_or_equal:today',
            'seats'       => 'required|array|min:1',
            'seats.*'     => 'required|string',
        ]);

        // 2. Fetch the Schedule (to get the real price)
        $schedule = Schedule::with('bus')->findOrFail($request->schedule_id);

        // 3. Check Seat Availability (Critical Safety Check)
        // We check if ANY of the requested seats are already taken for this specific date
        $takenSeats = Ticket::whereHas('booking', function ($q) use ($request) {
            $q->where('schedule_id', $request->schedule_id)
            ->where('travel_date', $request->travel_date)
            ->where('status', '!=', 'cancelled'); // Ignore cancelled bookings
        })
        ->whereIn('seat_number', $request->seats)
        ->exists(); // Returns true if even ONE seat is taken

        if ($takenSeats) {
            return response()->json(['message' => 'One or more selected seats are already booked.'], 409); // 409 Conflict
        }

        // 4. Calculate Total Price (Server Side)
        // Never trust the price sent from the frontend!
        $totalPrice = $schedule->price_per_seat * count($request->seats);

        // 5. The Transaction
        $booking = DB::transaction(function () use ($request, $schedule, $totalPrice) {
            
            // A. Create the Booking Record
            $booking = Booking::create([
                'account_id'  => $request->user()->id,
                'schedule_id' => $schedule->id,
                'booking_date' => now(), // Date when booking was made
                'travel_date' => $request->travel_date, // Date when the trip will take place
                'status'      => 'confirmed', // Assuming direct confirmation for now
                'total_amount' => $totalPrice,
            ]);
            
            // Re-fetch to get the ID generated by Trigger
            $booking = Booking::where('account_id', $request->user()->id)->latest()->first();

            // B. Create the Individual Tickets
            foreach ($request->seats as $seatNum) {
                Ticket::create([
                    'booking_id'  => $booking->id,
                    'passenger_name' => $request->user()->first_name . ' ' . $request->user()->last_name,
                    'seat_number' => $seatNum,
                    'status'      => 'confirmed'
                ]);
            }

            // C. Send Notification (Inside transaction for safety)
            // If the notification fails (e.g. database error), the whole booking rolls back.
            $request->user()->notify(new BookingConfirmed($booking));

            return $booking;
        });

        // 6. Return Response
        // We reload the booking with relations so the frontend gets full details immediately
        return response()->json([
            'message' => 'Booking successful',
            'data'    => $booking->load(['schedule.route.destination', 'tickets'])
        ], 201);
    }

    // GET /api/my-bookings
    public function index(Request $request)
    {
        $bookings = Booking::with([
            'tickets',
            'schedule.route',
            'schedule.bus'
        ])
        ->where('account_id', $request->user()->id)
        ->orderBy('booking_date', 'desc')
        ->get();

        return response()->json($bookings);
    }

    public function cancel(Request $request, $id)
    {
        // 1. Find the booking belonging to the logged-in user
        $booking = Booking::where('id', $id)
                        ->where('account_id', $request->user()->id)
                        ->with(['schedule', 'payment']) // Load relations we need to check
                        ->first();

        if (!$booking) {
            return response()->json(['message' => 'Booking not found.'], 404);
        }

        // 2. Check if it's already cancelled or completed
        if ($booking->status === 'cancelled') {
            return response()->json(['message' => 'Booking is already cancelled.'], 400);
        }
        if ($booking->status === 'completed') {
            return response()->json(['message' => 'Cannot cancel a completed trip.'], 400);
        }

        // 3. Time Limit Check (Optional but Recommended)
        // Combine the date and time to create a Carbon object
        // Assuming booking has 'travel_date' and schedule has 'departure_time'
        // Combine the date and time to create a Carbon object
        // We use travel_date from booking and time from schedule
        $departureTimestamp = Carbon::parse($booking->travel_date . ' ' . Carbon::parse($booking->schedule->departure_time)->format('H:i:s'));
        
        // If departure is less than 24 hours from now
        if ($departureTimestamp->lessThan(now()->addHours(24))) {
            return response()->json(['message' => 'Cancellation is only allowed 24 hours before departure.'], 400);
        }

        // 4. The Atomic Transaction
        DB::transaction(function () use ($booking) {
            
            // A. Update Booking Status
            $booking->update(['status' => 'cancelled']);

            // B. Update/Delete Tickets (Free up the seats)
            // We usually don't DELETE rows (hard delete) for history purposes.
            // Instead, we mark them as cancelled so the seat logic ignores them.
            $booking->tickets()->update(['status' => 'cancelled']);

            // C. Handle Payment/Refund Logic
            if ($booking->payment && $booking->payment->status === 'paid') {
                $booking->payment->update(['status' => 'refund_pending']);
                // logic to trigger Stripe/Gateway refund would go here
            }
        });

        return response()->json(['message' => 'Booking cancelled successfully. Refund processing started.']);
    }
}