<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Bus>
 */
class BusFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {
        return [
            // ID is auto-generated by DB Trigger (BUSxxx)
            'bus_number' => $this->faker->unique()->bothify('B #### ??'), // e.g., B 1234 AB
            'bus_type' => $this->faker->randomElement(['Economy', 'Business', 'VIP', 'Sleeper']),
            'capacity' => 40,
            'quota' => 40,
            'seat_rows' => 10,
            'seat_columns' => 4,
            'remarks' => $this->faker->sentence(),
        ];
    }
}
